development:
  adapter: postgresql
  encoding: utf-8
  database: blog_dev
  host: localhost
  pool: 64
  timeout: 5000
  username: myapp
  password: 1q1q

test:
  adapter: postgresql
  encoding: utf-8
  database: blog_test
  host: localhost
  pool: 64
  timeout: 5000
  username: myapp
  password: 1q1q

production:
  adapter: postgresql
  encoding: utf-8
  database: blog_prod
  host: localhost
  pool: 64
  timeout: 5000
  username: myapp
  password: 1q1q